smptdServer:
  address: ":2525"                # Service listening address
  debug: true                     # Enable debug mode
  appname: "MyServerApp"         # Server application name
  hostname: ""                    # Server hostname (empty for auto-detection) e.g.: "mail.example.com"

smtpdTLS:
  enabled: true                   # Enable TLS
  cert: "/opt/mitmsmtpd/tls/mail.pem"     # Path to TLS certificate
  key: "/opt/mitmsmtpd/tls/mail-key.pem"  # Path to TLS private key

smtpdAuth:
  mechanisms:                     # Supported authentication mechanisms
    "LOGIN": true  
    "PLAIN": false
    "CRAM-MD5": false
  required: true                  # Require authentication
  allowAnyAuth: true                # Allow authentication through any username and password.

logging:
  path: "/tmp/"    # Log directory
  filename: "app.log"            # Log filename

userDB:                          # username: password
  "user01@example.com": "123456"
  "user02@example.com": "12345678"
  "admin@test.org": "securePass"


# By using the sender's email address, determine the actual email server address (this service acts as an intermediary)
# The value of authMechanisms is one of LOGIN CRAM-MD5 PLAIN.
emailServer:
  "example.com": 
    server: "smtp.example.com"
    port: 587
    authMechanisms: "PLAIN"  
  "mymail.com": 
    server: "smtp.office365.com"
    port: 587
    authMechanisms: "LOGIN"  

# 再发送邮件前先进行探测，确保邮件服务器可用。如果部署在内网，并且邮件服务器的dns的A解析变化时，内网防火墙无法及时更新白名单，导致发送邮件失败。
smtpProbe:
  enable: true        # 是否启用邮件服务器探测
  retryInterval: 60   # 重试间隔，单位：秒
  maxRetry: 10        # 最大重试次数
  
verificationRules:  
  sender: "^(.*@example\\.com|.*@mymail\\.com)$"               # Allowed sender regex pattern (reject if not matched)
  recipient: "^(.*@example\\.com|.*@mymail\\.com)$"            # Required recipient regex pattern (all recipients must match)
  senderIP: "^(127\\.0\\.0\\.1|10\\.10\\.20\\.11)$"  # Allowed client IP regex (reject all if not matched)
  emailBodySize: 0                       # Max email body size in bytes (0=unlimited)
  attachment:
    allowed: true                            # Whether attachments are permitted (default: false)
    maxSize: 0                             # Max attachment size in bytes (0=unlimited)
  embeddedContent:                           # Embedded elements in email body (e.g., images)
    allowed: true                            # Whether embedded content is permitted (default: false)
    maxSize: 0                          # Max embedded content size in bytes (0=unlimited)

# verificatioRules:
#   sender: "^.*@example\\.com$"              # 允许的发件人，不匹配此正则表达式则拒绝
#   recipient: "^*.@example\\.com$"           # 收信人有多个，每个都需要匹配此正则，否则拒绝
#   senderIP: "^(127\\.0\\.0\\.1|10\\.10\\.20\\.11)$"   # 发件人的IP地址，每个收信人都需要匹配此正则，不匹配则全部拒绝
#   emailBodySize: 1024                     # 邮件内容大小，单位Bytes，超过此值则拒绝，默认为0，不限制大小
#   attachment:                             # 附件  
#     enabled: false                        # 是否允许有附件，默认为false，不允许
#     size: 1024                            # 附件大小，单位Bytes，如果允许有附件且大小超过此值则拒绝，默认为0，不限制大小    
#   emailBodyEmbedded:                      # 邮件正文嵌入的元素(一般为图片)  
#     enabled: false                        # 是否允许邮件正文嵌入元素，默认为false，不允许 
#     size: 1024                            # 邮件正文嵌入元素大小，单位Bytes，如果允许嵌入元素且大小超过此值则拒绝，默认为0，不限制大小  

# Exception notification - Email or ...
notification:
  email:
    enabled: true
    from: "it-report@mymail.com"
    password: "xxxxx"
    server: "smtp.office365.com"
    port: 587
    to: ["userwu@mymail.com"]
    cc: ["userwutest@mymail.com"]
    subject: "Mail Gateway Abnormality"
  sms:
    enabled: true
    xxx: "xxxxx"
    xxxx: "xxxxx"

